# Generated by Django 4.2.dev20220603193729 on 2022-06-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0002_producto_iagen"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto", old_name="iagen", new_name="imagen",
        ),
    ]
