# Generated by Django 4.2.dev20220603193729 on 2022-06-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0003_rename_iagen_producto_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Direccion"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="telefono",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Telefono"
            ),
        ),
    ]
